### ISSUE TITLE
changing format of adding stuff

### ISSUE THREAD

**Issue by thevasudevgupta** [analytics-club-iitm/Paper-Archive#1]
Hey, is it fine if I follow the different format to add papers summaries. Like [Paper Name] [Paper Link] [Paper.md]. and all assets in single folder. Its easy to follow this format 😅😅. And can summaries be just brief points relevant to paper?

**Comment by MukundVarmaT** [comment]
yeah sure! but assets in one folder will be quite chaotic if someone else tries to add some papers as well. But if you are comfortable with that its fine :)
